#!/usr/bin/env python3
"""Generate the analytics-rule catalog."""

from __future__ import annotations

import argparse
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "rule-catalog.md"


def build() -> str:
    lines = ["# Analytics Rule Catalog", "", "Generated by `scripts/generate_catalog.py`; do not edit manually.", "",
             "| Rule | Domain | Severity | Tables | ATT&CK | Entities | Version |",
             "|---|---|---|---|---|---|---|"]
    for path in sorted((ROOT / "analytics-rules").rglob("*.yaml")):
        rule = yaml.safe_load(path.read_text(encoding="utf-8"))
        rel = path.relative_to(ROOT).as_posix()
        tables = sorted({table for item in rule["requiredDataConnectors"] for table in item.get("dataTypes", [])})
        entities = [item["entityType"] for item in rule.get("entityMappings", [])]
        values = [f"[{rule['name']}](../{rel})", path.parent.name, rule["severity"], ", ".join(tables),
                  ", ".join(rule.get("relevantTechniques", [])) or "—", ", ".join(entities), rule["version"]]
        lines.append("| " + " | ".join(str(v).replace("|", "\\|") for v in values) + " |")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = build()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print("Rule catalog is stale. Run: python3 scripts/generate_catalog.py")
            return 1
        print("Rule catalog is current.")
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
